src/extension.ts
src/helpers/required.ts

A new await command was added on `checkApps(...requiredApps);`
The `required.checkAllApps();` was put at the beginning of the extension page, before all the initialize functions

fix: Preventing possible bug on required apps

---

package.json
src/commands/TruffleCommands.ts
src/views/FileExplorer.ts

Bug fix to solve the right click on Explorer view
The Explorer Tree Item has been composing by [uri, filetype], once the VSCode Tree Item has been composing only by uri.
I've built a parser to solve it as a workaround. If we can create a pattern for all Tree Items, is better. We avoid to change the build / deploy code.
Add-ons:
I've put the deploy command on the right click button on Explorer View.

fix: workaround for build/deploy commands in explorer view

---

src/commands/TruffleCommands.ts
src/helpers/truffleConfig.ts
src/helpers/workspace.ts

When users tried to run build/deploy, an error occurred: spawn C:\WINDOWS\system32\cmd.exe ENOENT
Issue: https://github.com/trufflesuite/vscode-ext/issues/108
The issue was found on windows 11 platform only. It was related to volume mapping. If the user open a project in root, the build/deploy command works fine. But, if it was opened in a mapping volume, the problem occurred. A fix was made and applied for windows platforms only.

fix: build/deploy fix for windows

---

resources/welcome/prereqs.html

The required apps page displays only the minimum version of apps. To avoid misunderstandings, it might be better to display the maximum version as well.
Issue: https://github.com/trufflesuite/vscode-ext/issues/117

Edit the required apps page to display the version range of all apps

---

src/Constants.ts
src/helpers/checkTruffleConfigTemplate.js
test/TruffleCommandsTests/testData/truffle-config.js

Debugger doesn't work when using HDWalletProvider in your truffle-config.js
The hdwalletNodeModulePath has updated to @truffle/hdwallet-provider
Issue: https://github.com/trufflesuite/vscode-ext/issues/87

fix: hdwallet npm package has updated to truffle/hdwallet-provider

---

src/Models/IDeployDestination.ts
src/Models/TreeItems/LocalProject.ts
src/commands/TruffleCommands.ts

When you try to deploy a contract on a forked network, the system starts it as a standard non-forked network
Related to: https://github.com/trufflesuite/vscode-ext/issues/140

fix: contract deployment is not forking networks

---

src/Constants.ts
src/debugAdapter/constants/truffleConfig.ts
src/debugAdapter/contracts/contractsPrepareHelpers.ts
src/debugAdapter/debugNetwork.ts
src/debugAdapter/debugSession.ts
src/debugAdapter/runtimeInterface.ts
src/debugAdapter/transaction/transactionProvider.ts
test/debugAdapter/runtimeInterface.test.ts

Debug transaction is working with Ganache development instance only. If a new Ganache instance is created with another name, and a new contract is sent to it, a Debug attempt causes a system error.
A network selector has implemented to allow users choose your network before starting debugging
Refer to: https://github.com/trufflesuite/vscode-ext/issues/141

Debug only works with Ganache Development Instance

---

package.json
src/services/infuraService/codeFlowLogin.ts
yarn.lock

This PR uses the recommended way to open external links. See `openExternal` in https://code.visualstudio.com/api/references/vscode-api#env.
Now when the user selects Infura sign-in, a prompt should appear confirming opening the external link https://code.visualstudio.com/updates/v1_38#_link-protection-for-outgoing-links. It partially solves comment https://github.com/trufflesuite/vscode-ext/issues/175#issuecomment-1203896606.
Moreover, it removes the `open` package, since it is not used anymore.

Replace `open` package with `vscode.env.openExternal`

---

.vscodeignore

This PR adds an entry for Mocha config (`.mocharc.js`) to `.vscodeignore`, so that it will not be packaged into the extension when issuing `vsce package`.

Remove Mocha config from packaged extension

---

tsconfig.json

This PR removes the `dom` entry from `lib` in `tsconfig.json`, since it is not needed. The runtime environment for the extension is provide by VS Code, and does not contain the `dom` library.
Moreover, if `dom` is declared, autocompletion assumes that `window` refers to the `dom` and not the VS Code API, which is a bit annoying.
By removing `dom` from `tsconfig`, autocompletion will use the right `window` namespace from VS Code's API.

Remove unused `dom` `lib` from `tsconfig`

---

src/commands/DebuggerCommands.ts

When you redeploy a contract without restarting the network, duplicate transactions show up in the dialog when selecting a txhash via Truffle: Debug Transaction, for example. Note that the "legacy" txns don't include the contract name.

Remove redundant txns from dialog after a redeploy

---

package.json
src/Constants.ts
src/Models/StatusBarItems/Contract.ts
src/commands/ContractCommands.ts
src/commands/TruffleCommands.ts
src/extension.ts
src/helpers/workspace.ts
src/services/contract/ContractService.ts
test/TruffleCommandsTests/WriteToBuffer.test.ts

ref: #211
The automatic deploy functionality for contracts was developed and implemented as a status bar item.

Create an "auto-deploy on save" toggle in the Contract Explorer

---

src/Constants.ts

ref: #235
Spurious closing bracket on "Create sample project" has been fixed

Spurious closing bracket on "Create sample project" entry when creating a new project

---

src/Output.ts
src/commands/TruffleCommands.ts
src/extension.ts
src/services/dashboard/DashboardService.ts
src/services/ganache/GanacheService.ts
src/views/LogView.ts
test/commands/GanacheService.test.ts
test/commands/ProjectCommand.test.ts

ref: #234
As requested, I've rolled back the log while retaining the **Truffle Panel Log** in passive mod and utilising output channels. To preserve the genuine user experience, all regulations were reinstated and upheld. To make it simple to remove (or keep) the old log code in the future, I've marked it with the following text: `// INFO: THIS IS THE OLD VERSION OF LOGGER USING OUTPUT CHANNELS`

Temporarily continue logging to the Truffle for VS Code output channel

---

webpack.common.js
webpack.prod.js

The`devtool` option was changed from `source-map` to `eval`. We know that this may not be the best option, however, the memory of the virtual machines was overflowing due to the large use of resources to generate the code mapping.

Fix: Webpack options

---

.vscode/settings.json
src/Constants.ts
src/views/FileExplorer.ts
src/views/Utils.ts

Issue ref: #248
When more than one workspace is opened on Visual Studio Code, the Explorer View does not find the contract folder. This patch fixes this situation and displays the directory regardless of location

Contracts not detected

---

package.json
src/commands/DebuggerCommands.ts
src/debugAdapter/debugNetwork.ts
src/debugAdapter/models/debuggerTypes.ts
src/helpers/uriHandlerController.ts
test/commands/DebuggerCommands.test.ts

This PR contains some improvements to the routine responsible for handling the calls addressed to vscode protocol. It also fixes some bugs and implements a new parameter to the debuger configuration. Below is the list of changes:
I've made a simple modification to support windows command prompt calls. Command prompt does not support sending Json Objects on URL so I had to change the arguments from object to querystring params. Unfortunately, the Windows command prompt does not support sending an URL with Json Objects.
Before: `{"txHash":"0x97a81dbca1ea95263bb75b0147c99f263fe21cf702abe8974c310c9fa834d9b9","workingDirectory":"/Users/xhulz/Documents/xpto","providerUrl":"[http://127.0.0.1:8545"}](http://127.0.0.1:8545%22%7D/)`
Now: `"txHash=0x4d1f42a6096f82e01a680a7364e958f9214447473e025f8f00f …

Running truffle debug with appropriate flag (--vscode) - Enhancements & Fixes

---

package.json
src/commands/DebuggerCommands.ts
src/debugAdapter/debugNetwork.ts
src/debugAdapter/runtimeInterface.ts
src/debugAdapter/types/@truffle/debugger.d.ts
src/functions/explorer.ts
src/helpers/ConfigurationReader.ts
test/commands/DebuggerCommands.test.ts
yarn.lock

This PR closes #149. It uses the Truffle `fetch-and-compile` module to fetch external sources when debugging a forked network.
Currently it serializes the external sources in a temporary folder.
Whenever the path of a contract being serialized is a nested path, _.e.g._, `/@openzeppelin/contracts/access/Ownable.sol`,
the contract is serialized using its full path.

Fetch external sources when debugging a forked network

---

webpack.common.js

This PR removes the `prettier` package from the extension bundle. `prettier` is actually not used by the extension. However there is a transitive dependency from `@truffle/resolver`
```sh
$ yarn why prettier
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "prettier"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "prettier@2.7.1"
info Has been hoisted to "prettier"
info Reasons this module exists
- Specified in "devDependencies"
- Hoisted from "@truffle#resolver#abi-to-sol#prettier"
info Disk size without dependencies: "15.16MB"
info Disk size with unique dependencies: "15.16MB"
info Disk size with transitive dependencies: "15.16MB"
info Number of shared dependencies: 0
✨  Done in 0.31s.
```

Remove `prettier` from bundle

---

package.json
src/debugAdapter/runtimeInterface.ts
src/debugAdapter/types/@truffle/debugger.d.ts
yarn.lock

This PR closes #263. After updating both `package.json` and `yarn.lock`, `faker` is not included anymore in the bundle. Run the following to check that `faker` was effectively removed
```sh
$ yarn webpack:dev
$ cat out/src/extension.js | grep faker | wc -l
1
```
this result is just metadata
```
module.exports = JSON.parse('{[...]"devDependencies":{"@types/faker":"^5.1.2"[...]}');
```
and 
```sh
$ yarn why faker
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "faker"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.32s.
```
Debugger typings must be updated since bumping to `11.0.17` is breaking change as described here https://github.com/trufflesuite/truffle/pull/5286#issuecomment-1184020915 and …

Update `@truffle/debugger` to remove `faker` in bundle

---

src/Constants.ts

Both Truffle and Ganache allows to use Node 18. This PR allows the user to use Node 18 as well.

Allow Node v18 in Required Apps

---

package.json

This PR declares the newly added `network` option https://github.com/trufflesuite/vscode-ext/pull/261 in the [launch configuration](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations).
https://user-images.githubusercontent.com/4592980/203780382-c6bca2b8-8633-4baf-bbb2-7c685775acdd.mp4
Moreover, it includes a new configuration snippet that uses the `network` option instead of `providerUrl`
https://user-images.githubusercontent.com/4592980/203783922-ad44b98a-4fbe-4ee2-87dc-2d1e7c9a26b2.mp4

Declare `network` option in launch configuration

---

.github/workflows/core-ci-checks.yml
webpack.prod.js

This PR is a follow-up of https://github.com/trufflesuite/vscode-ext/pull/245. The main goal is to improve performance, more specifically, when activating the extension by reducing package size. See https://github.com/trufflesuite/vscode-ext/pull/245#issuecomment-1326630850 for more details.
Moreover, it builds the `vsix` package in CI as a smoke check.

Remove `devtool` from production bundle

---

src/debugAdapter/runtimeInterface.ts

This PR closes #262. Essentially duplicates the changes made in https://github.com/trufflesuite/truffle/pull/5728. This means that if https://github.com/trufflesuite/truffle/pull/5728 gets merged we can revert the changes of this PR.

Invalidate `require` cache of `truffle-config.js`

---

resources/welcome/prereqs.html

This PR clarifies that the extension depends on Ganache CLI, as opposed to Ganache UI., in the `Requirements Page`.

Clarify Ganache CLI usage in `Requirements Page`

---

CHANGELOG.md

This PR includes changes to be published in `2.7.0` release, codenamed _Aranha_.
This release brings some new exciting features regarding the debugger, namely it allows you to fetch external sources when debugging external transactions, reuse your `truffle-config.js` networks to debug a transaction and trigger the visual debugger from the command line. It also includes a fix that removes deprecated networks after the merge and a range of smaller fixes and improvements.
Give it a try and let us know what you think!
- Clarify Ganache CLI usage in `Requirements Page` [\#274](https://github.com/trufflesuite/vscode-ext/pull/274) ([acuarica](https://github.com/acuarica))
- Allow Node v18 in Required Apps [\#272](https://github.com/trufflesuite/vscode-ext/pull/272) …

Add Changelog from `2.7.0` release

---

.eslintrc.js

This PR enables ESLint's `@typescript-eslint/recommended-requiring-type-checking` rules so we can start reducing technical debt. Given that we have many issues, rules appearing mostly in tests have been disabled. The rest of the rules have been enabled but with warnings so they don't get in the way. The idea is to at least gain some visibility on what issues we have and what we can improve.
I understand that this can be annoying, that's why if this gets merged, would be nice to have at least 2 approvals. @michaeljohnbennett @kevinbluer @xhulz thoughts on this?

Enable ESLint's recommended type checking rules using `warn`
